#!/usr/bin/env python
import gtk
execfile("hello.py")
class PyApp(gtk.Window):

    def __init__(self):
        super(PyApp, self).__init__()
        self.set_border_width(8)
        self.set_title("Search engine")
        self.set_size_request(550, 550)
        self.set_position(gtk.WIN_POS_CENTER)

        vbox = gtk.VBox(False, 2)
        
        mb = gtk.MenuBar()
        filemenu = gtk.Menu()
        filem = gtk.MenuItem("File")
        filem.set_submenu(filemenu)
        mb.append(filem)

        vbox.pack_start(mb, False, False, 0)

        table = gtk.Table(8, 8, True)
        tview = gtk.TextView()
        
		#background
        tview.modify_base(gtk.STATE_NORMAL,gtk.gdk.color_parse('#DDCCEE'))
		#foreground
        tview.modify_text(gtk.STATE_NORMAL,gtk.gdk.color_parse('#FFFFFF'))
		#bonus font
        #tview.modify_font(pango.FontDescription('Monospace 11'))
        #table.attach(tview, 1, 8, 1, 7)
        lview=gtk.Label("search by:")
        #lview.modify_bg(gtk.STATE_NORMAL,gtk.gdk.color_parse("blue"))
		#foreground
        #lview.modify_text(gtk.STATE_NORMAL,gtk.gdk.color_parse('#FFFFFF'))
        map = lview.get_colormap()
        colour = map.alloc_color("blue")
        table.attach(gtk.Entry(max=30), 0, 7, 0, 1)
        table.attach(lview, 0, 1, 1, 2)
        def blink():
        	return ("facebook")
        #table.attach(gtk.Button("."), 1, 2, 4, 5)
        search=gtk.Button("search")
        search.connect("clicked",blink)
        table.attach(search, 7, 8,0,1)  
        table.attach(gtk.Button("prev"), 6, 7, 7, 8)
        table.attach(gtk.Button("next"), 7, 8, 7, 8)
        table.attach(gtk.CheckButton("check button 1"),0,1,2,3)
        table.attach(gtk.CheckButton("check button 1"),0,1,3,4)
        table.attach(gtk.CheckButton("check button 1"),0,1,4,5)
        table.attach(gtk.LinkButton("www.google.com",blink()),1,2,1,2)
        table.attach(gtk.LinkButton("abg.png","google"),2,3,1,2)
        table.attach(gtk.LinkButton("abg.png","google"),3,4,1,2)
        table.attach(gtk.LinkButton("abg.png","google"),4,5,1,2)
        table.attach(gtk.LinkButton("abg.png","google"),5,6,1,2)
        table.attach(gtk.LinkButton("abg.png","google"),6,7,1,2)
        table.attach(gtk.LinkButton("abg.png","google"),7,8,1,2)

           	
     #'''table.attach(gtk.LinkButton("abg.png","google"),0,1,5,6)
      #  table.attach(gtk.LinkButton("abg.png","google"),0,1,5,6)
       # table.attach(gtk.LinkButton("abg.png","google"),0,1,5,6)
        #table.attach(gtk.LinkButton("abg.png","google"),0,1,5,6)
        #table.attach(gtk.LinkButton("abg.png","google"),0,1,5,6)
        #table.attach(gtk.LinkButton("abg.png","google"),0,1,5,6)'''
        table.attach(gtk.CheckButton("check button 1"),0,1,5,6)
        cb = gtk.combo_box_new_text()
        #cb.connect("changed", self.on_changed)

        cb.append_text('Ubuntu')
        cb.append_text('Mandriva')
        cb.append_text('Redhat')
        cb.append_text('Gentoo')
        cb.append_text('Mint')
#vbox.pack_start(gtk.Entry(), 0, 1, 1)
        table.attach(cb,0,1,6,7)
        vbox.pack_end(table, True, True, 0)

        self.add(vbox)

        self.connect("destroy", gtk.main_quit)
        self.show_all()
        

PyApp()
gtk.main()
